version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: deploy-scripts/kill_container.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: deploy-scripts/load_image.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: deploy-scripts/start_container.sh
      timeout: 120
      runas: root
