version: 0.0
os: linux
files:
  - source: release
    destination: /var/minimalApi
  - source: deploy-scripts/minimalapi.service
    destination: /etc/systemd/system
hooks:
  BeforeInstall:
    - location: deploy-scripts/before_install.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: deploy-script/stop_app.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: deploy-scripts/start_app.sh
      timeout: 120
      runas: root
