version: 0.0
os: linux
files:
  - source: deploy-scripts/minimalapi.service
    destination: /etc/systemd/system
  - source: deploy-scripts/start_minimalApi.sh
    destination: /usr/bin
hooks:
  ApplicationStop:
    - location: deploy-scripts/kill_container.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: deploy-scripts/load_image.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: deploy-scripts/start_container.sh
      timeout: 120
      runas: root
