version: 0.2

phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel STS

  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - dotnet restore MinimalApi/MinimalApi.sln

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - dotnet build MinimalApi/src/MinimalApi.sln

  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
