version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: latest

  pre_build:
    commands:
      - dotnet restore MinimalApi/MinimalApi.sln
      - dotnet test MinimalApi/MinimalApi.sln

  build:
    commands:
      - dotnet build

  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
