version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: latest

  pre_build:
    commands:
      - dotnet restore
      - dotnet test

  build:
    commands:
      - dotnet build

  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
